name: build
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@master
        with:
          platforms: ppc64le,s390x
      - uses: docker/setup-buildx-action@master
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: https://github.com/mailhog/MailHog.git
          platforms: linux/amd64,linux/ppc64le,linux/s390x
          tags: ghcr.io/${{ github.repository }}
          push: true
